import { ClientProviders } from "@shared/components/ClientProviders";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@ui/components/Toaster";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import "../../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const queryClient = new QueryClient();
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <ClientProviders>
          <body className={`${GeistSans.variable} bg-background font-sans`}>
            <NextTopLoader color={"var(--colors-primary)"} />
            {children}
            <Toaster />
          </body>
        </ClientProviders>
      </QueryClientProvider>
    </html>
  );
}
