import { ClientProviders } from "@shared/components/ClientProviders";
import { Toaster } from "@ui/components/Toaster";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import "../../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`${GeistSans.variable} bg-background font-sans`}>
        <NextTopLoader color={"var(--colors-primary)"} />
        <ClientProviders>{children}</ClientProviders>
        <Toaster />
      </body>
    </html>
  );
}
